# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x AddictionBreaker/gradlew
    - name: Build with Gradle
      run: AddictionBreaker/gradlew build
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: "43b178f1-fb4c-4766-8336-bb249a9edd2f"
        MESSAGE: "Hey Thinh, there's a new build!"
